name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.5

      - name: Install deps
        run: bun i

      - name: Lint
        run: bun run lint

      - name: Check format
        run: bun run format

      - name: Run tests
        run: bun run test

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build Docker images
        run: docker compose build

      - name: Start Docker services
        run: docker compose up --renew-anon-volumes -d

      - name: Install Playwright Browsers
        working-directory: e2e
        run: bunx playwright install --with-deps

      - name: Run e2e tests
        env:
          BASE_URL: http://localhost:8081
        run: bun run test:e2e

      - name: Stop Docker services
        run: docker compose down

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker images to GitHub Container Registry
        run: |
          docker tag dev-academy-web:latest ghcr.io/${{ github.repository_owner }}/dev-academy-web:latest
          docker tag dev-academy-backend:latest ghcr.io/${{ github.repository_owner }}/dev-academy-backend:latest
          docker tag dev-academy-db:latest ghcr.io/${{ github.repository_owner }}/dev-academy-db:latest
          docker push ghcr.io/${{ github.repository_owner }}/dev-academy-web:latest
          docker push ghcr.io/${{ github.repository_owner }}/dev-academy-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/dev-academy-db:latest
